version: '3.8'

services:
  techflow:
    image: virgoooox/techflow:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./data/database.db
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped